### ISSUE TITLE
API 建议（长期补充）

### ISSUE THREAD

**Issue by afc163** [react-component/tween-one#1]
1. `vars` 改为 `animation` 或 `keyframes`。
2. `type={start|pause|reverse|restart}` 不是声明式的语法，可以拆为 `paused={true|false}` `reverse={true|false}`。可加入时间轴的参数来控制动画的状态。
   ```jsx
   <Tween defaultMoment={0}></Tween>
   ```

   ```jsx
   onChange(moment) {
      this.setState({ moment });
   }
   ...
   <Tween moment={this.state.moment} onChange={this.onChange}></Tween>
   ```
   
   > moment 表示动画当前运行到的总时刻

3. `vars` 里的 type 感觉没用。
4. `vars` 的 `onXxxx` 可以都提到 Tween 上面的 onChange，相关信息放在参数里。

```js
onChange(moment, currentKeyframe) {
  // currentKeyframe
  // currentKeyframe.currentDuration => currentDuration
}
```

**Comment by jljsj33** [comment]
3。vars 里的 type 有用的。。

**Comment by jljsj33** [comment]
4.这块难搞把。。如果单个动画参数是可以的。。。时间轴时就不行了吧。。我当初也想提出来的。。。发现如果有4个，，那我要在第3个参数结束后调用。。。如果在外面不就要算了？？？

**Comment by afc163** [comment]
可以加一个。

```js
onChange(moment, currentKeyframe, index) {
  // currentKeyframe
  // currentKeyframe.currentDuration => currentDuration
}
```

**Comment by hi-caicai** [comment]
Please make  a simple API

**Comment by jljsj33** [comment]
Please speak Chinese!
