### ISSUE TITLE
Please replace findDOMNode with safe Refs

### ISSUE THREAD

**Issue by cangSDARM** [react-component/tween-one#118]
![image](https://user-images.githubusercontent.com/20441896/118097920-de290b00-b405-11eb-8f6b-2be40c4166a4.png)

I think this will be a problem in the near or far future, and it's not a good design.

So, please replace findDOMNode with safe refs

**Comment by jljsj33** [comment]
use 3.0.0-beta.8，，，https://github.com/react-component/tween-one/pull/102

**Comment by cangSDARM** [comment]
How long will it take to merge to the main branch, or how long will it take to release a stable version?

**Comment by jljsj33** [comment]
Because of this connection, other animations have a lot of inventory and changes. This is a brand new warehouse. There may be problems during this period of time, so I need to use it first, and then check it slowly. 
Or if you have problems in using it, please contact us.

**Comment by cangSDARM** [comment]
Ok then, i will close this

**Comment by ljx0520** [comment]
> use 3.0.0-beta.8，，，#102

Hi

I got the same bug when I use Overpack in package rc-scroll-anim, how did you fix it? Any advice would be appreciated. Thanks in advance.
