### ISSUE TITLE
useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by congwa** [react-component/tween-one#133]
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.

**Comment by jljsj33** [comment]
https://github.com/react-component/tween-one/pull/132
