### ISSUE TITLE
NextJS TweenOne useEffectLayout Warning

### ISSUE THREAD

**Issue by jellohouse** [react-component/tween-one#134]
I'm getting this warning in the console:

`Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client.`

Anyone else having this issue? 
Is there a good way to solve this?

**Comment by jljsj33** [comment]
https://github.com/react-component/tween-one/pull/132
