### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by Seasons123** [react-component/tween-one#16]
用react来做动画，除了可以封装成组件提高团队的开发效率，还有什么优势么？

**Comment by jljsj33** [comment]
封装成组件后，以简单方便，可组合使用 与复用，提升效率，结合react 特性，可以灵活的控制动画。。如animate 控制 css 动画，只需要你配置好动画样式即可完成进入与消毁时的动画。不过用 js 动画方面在性能效率方面真的没什么优势，只有劣势，，哈哈，，setState 效率真的不咋的，每次都要渲染 dom，500 个元素测试完全没法跑，，所以 tween-one 在 0.4 以后还是选择了用 dom 来执行动画。。
