### ISSUE TITLE
IE 11 下报错

### ISSUE THREAD

**Issue by yesmeck** [react-component/tween-one#29]
https://github.com/react-component/tween-one/blob/master/src/plugin/StylePlugin.jsx#L258

`createMatrix` 可能返回 null

<img width="1360" alt="20180122115244" src="https://user-images.githubusercontent.com/465125/35204680-c71b513c-ff6a-11e7-9ee7-1ce195419045.png">

**Comment by jljsj33** [comment]
我擦。。。我看下。。。

**Comment by jljsj33** [comment]
删掉依赖重装一下。。
