### ISSUE TITLE
Is there any way to control when the animation begin on scroll?

### ISSUE THREAD

**Issue by darrylsepeda** [react-component/tween-one#31]
I found that the animation will start when the object is scrolled to the middle of the screen.
I tried to use playScale and other API to make the animation start when the object reach the bottom of the screen but none of the API is working.

Is there any way to make the animation works when object reach the bottom of the screen??

**Comment by jljsj33** [comment]
```jsx
<OverPack playScale={0.1} style={{ minHeight: 500}}>
   <TweenOne key="tween" animation={{ y: 30, opacity: 0, type: 'from' }} >test</TweenOne>
</OverPack>
```jsx

https://github.com/react-component/scroll-anim#element, use min-height,  OverPack box requires height.

**Comment by darrylsepeda** [comment]
thanks for the answer, actually I did in another way so I will close this issue.
