### ISSUE TITLE
null is not an object (evaluating 'this.target.ownerSVGElement')

### ISSUE THREAD

**Issue by Ancinek** [react-component/tween-one#32]
Hi!

First of all - awesome package. Make apps look really fancy with all those animations!

I've started receiving the following error:

    null is not an object (evaluating 'this.target.ownerSVGElement')

Tried to debug it for a long time. It just happens when I load the page that uses this package, but not always (approx. 10 out of 100 cases). Unfortunately that's all that I currently have.

Any ideas why it might be happening and what can I or we do to stop it?

**edit**
I've seen that it was the case of [PR27](https://github.com/react-component/tween-one/pull/27). What was the reason it was not an acceptable solution?

**Comment by jljsj33** [comment]
Can you tell me how you got the wrong report?

**Comment by jljsj33** [comment]
I once received the same error in the `route`, if there is uncertainty in the children, it is recommended to add a layer of div.

#### TweenOneGroup 

```jsx
<Router history={history}>
  <Route render={({ location }) => {
    const to = '/list';
    const key = location.pathname === '/' ? to : location.pathname;
    return (
      <TweenOneGroup
        appear={false}
        enter={{ y: 30, opacity: 0, type: 'from' }}
        leave={{ y: -30, opacity: 0 }}
      >
+        <div key={key} id={key}>
          <Switch location={location}>
            <Route path="/new" component={New} key="new" />
            <Route path="/edit" component={Edit} key="edit" />
            <Route path="/list" component={List} key="list" />
            <Route path="/video" component={Video} key="video" />
            <Route path="/result" component={Result} key="result" />
            <Redirect from="/" exact to={to} />
          </Switch>
+        </div>
      </TweenOneGroup>);
  }} />
</Router>
```

#### or simple demo TweenOne

```jsx
function Div() {
  return (null);
}

function Demo() {
  return (<TweenOne
    animation={{ x: 300 }}
-    component="" // remove component="" 
  >
    <Div>demo</Div>
  </TweenOne>);
}
```

**Comment by Ancinek** [comment]
The main problem with this issue is that I do not exactly know how to reproduce it.
When I enter a page when there is a `TweenOneGroup` used I get it once in a while, not like always.

I have `appear` set to `false` as in your examples. Also, the children are wrapped in `<div> tags, but without using the `component` prop.

What's more is that I never experienced it locally, but only in production environment.

**Comment by jljsj33** [comment]
I thought about it this, but need to consider that componentDidUpdate is not null.

**Comment by jljsj33** [comment]
1.8.0

**Comment by Ancinek** [comment]
That was quite a lot of changes for just this one line rarely messing up. Great work :tada: And BIG BIG thanks :)!

**Comment by jljsj33** [comment]
1.8.1... publish failure
