### ISSUE TITLE
Start Error 

### ISSUE THREAD

**Issue by zhaoyangsoft** [react-component/tween-one#38]
启动后访问页面不成功， 控制台报 Error 

![image](https://user-images.githubusercontent.com/1456421/43449528-3c83c810-94e3-11e8-9445-ecf350aedb86.png)

```javascript 
webpack: bundle build is now finished.
  <-- GET /
  --> GET / 200 12ms 11.04kb
  <-- GET /examples
  --> GET /examples 200 10ms 15.33kb
  <-- GET /examples/childrenUpdate.html
  xxx GET /examples/childrenUpdate.html 500 75s -

  Error: connect ETIMEDOUT 30.129.144.64:8100
      at Object._errnoException (util.js:1022:11)
      at _exceptionWithHostPort (util.js:1044:20)
      at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1198:14)
```
其中 错误提示 : 【Error: connect ETIMEDOUT 30.129.144.64:8100】
但我的Ip 是:  30.5.54.82

![image](https://user-images.githubusercontent.com/1456421/43449925-345f1058-94e4-11e8-842e-1aca8b31ec6d.png)

**Comment by jljsj33** [comment]
????这什么鬼？？？自已看下代理有没有问题，，删了再重装试试。。。。

**Comment by zhaoyangsoft** [comment]
en , 代理在事发时应排查过 无代理， 已经重新安装过， 

昨天发现 连接有些 wifi   DHCP 服务器 会自动分配一个 地址， 但和ifconfig 的地址 是不一致的；
其中一个解决方法:  
使用 127.0.0.1:8100 访问 ,  且配置 host 127.0.0.1 localhost 
即可成功访问具体的demo页面。
