### ISSUE TITLE
对于负数的处理方式

### ISSUE THREAD

**Issue by Vultur** [react-component/tween-one#46]
-1  符合预期，输出：-1.00
-1.11 不符合预期，输出： -1.00
-0.11 不符合预期，输出： 0.00
1.11 符合预期，输出： 1.11
0.11 符合预期，输出：0.11

**Comment by jljsj33** [comment]
？？？这是哪的输出？动画过程？

**Comment by Vultur** [comment]
> ？？？这是哪的输出？动画过程？

tween-one 数值变化
[https://motion.ant.design/components/tween-one#components-tween-one-demo-position](https://motion.ant.design/components/tween-one#components-tween-one-demo-position)

**Comment by jljsj33** [comment]
OK, 我处理一下
